name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

jobs:
  quality:
    name: Quality Gates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run quality pipeline
        run: npm run quality:all

      - name: Type usage audit
        run: npm run ci:type-sanity

      - name: Upload quality summary
        uses: actions/upload-artifact@v4
        with:
          name: quality-summary
          path: |
            docs/QUALITY_SUMMARY.md
            quality-report.json
          if-no-files-found: warn
